services:
    mapserver:
        container_name: mapservermr
        image: mapservermr:0.1
        #environment:
            #- http_proxy=$HTTP_PROXYCONF
            #- https_proxy=$HTTPS_PROXYCONF
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./conf/informix/ld.so.conf:/etc/ld.so.conf
            - ./conf/informix/odbc.ini:/etc/odbc.ini
            - ./conf/informix/odbcinst.ini:/etc/odbcinst.ini
            - ./conf/informix/sqlhosts:/var/informix/etc/sqlhosts
            - ./conf/build.sh:/opt/build.sh
            - /etc/localtime:/etc/localtime:ro
            - ./data/root:/root
            - ./conf/mapserver.conf:/opt/etc/mapserver.conf
            - ./conf/mapserver:/opt/etc/mapserver
            - ./conf/apache2.conf:/etc/apache2/apache2.conf
            - ./conf/mapcache.xml:/var/www/mapcache/mapcache.xml
            - "sshfsdata:/geodata:rw"
            - "sshfsdata:/datos/geodata:rw"

volumes:
  sshfsdata:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "$SSHFS_DATA_USER@$SSHFS_DATA_HOST:$SSHFS_DATA_DIR"
      password: $SSHFS_DATA_PASS
      allow_other: ""
